feat: add review and movie page to async data
htmlacademy-react/1138089-what-to-watch-9 pull request #13
Opened 2022-04-10 14:25 UTC by JDRkow

2022-04-10 18:40 UTC, ekazakov requested changes

2022-04-10 18:40 UTC, ekazakov commented on project/src/store/api-actions.ts
> +);
Собственно это и есть основной подход к асинхронности в редаксе. 
Обычно перед отправкой запроса(и при завершении) в апи диспатчат эшкен устанавливающй флаг «идет запрос»

```
 try {
     store.dispatch(setFilmLoading(true));
      const {data} = await api.get<Film>((`/films/${id}`));
      store.dispatch(setCurrentFilm(data));
      store.dispatch(setFilmLoading(false));
    } catch (error) {
      errorHandle(error);
      store.dispatch(setFilmLoading(false));
      store.dispatch(redirectToRoute('/404'));
    }
  }
```

2022-04-10 18:40 UTC, ekazakov commented on project/src/components/movie-page/movie-page.tsx
> +  if(typeof currentFilm === 'undefined'){
можно `if(!currentFilm)`

2022-04-10 18:40 UTC, ekazakov commented on project/src/components/movie-review-page/movie-review-page.tsx
> +                <cite className="review__author">{review.user}</cite>
user — это объект, тут д.б. `review.user.name`

2022-04-10 18:54 UTC, JDRkow commented on project/src/store/api-actions.ts
> +);
Да, но сам компонент работает синхронно, и если запросить в стейте данные до завершения диспатча, то поидее мы получим промис и компонент вывалится в ексепшен

2022-04-11 07:10 UTC, ekazakov commented on project/src/store/api-actions.ts
> +);
Да, все верно. Реакт сам не обрабатывает асинхронность и надо проверять наличие данных самому.

На самом деле у реакта есть поддержка работы с асинхронностью., До недавнего релиза(18 версия) она была экспериментальная. Тут подробнее https://blog.logrocket.com/react-suspense-data-fetching/

2022-04-11 07:10 UTC, merged