feat(reducer): add show more button
htmlacademy-react/1138089-what-to-watch-9 pull request #9
Opened 2022-04-06 16:05 UTC by JDRkow

2022-04-06 18:50 UTC, ekazakov requested changes

2022-04-06 18:50 UTC, ekazakov commented on project/src/store/reducer.ts
>    films: films,
Фильмы в сторе инициализируй пустым массивом, моки уже можно удалять

2022-04-06 18:50 UTC, ekazakov commented on project/src/store/reducer.ts
>    films: films,
Еще в моках у фильма поле `directors`, а с сервера приходит `director` и оно строка, а не массив. Из-за этого в MoviePageOverview вылезает ошибка

2022-04-07 15:39 UTC, JDRkow commented on project/src/store/reducer.ts
>    films: films,
> Фильмы в сторе инициализируй пустым массивом, моки уже можно удалять

Я таким образом контракт оставил, определив проперти объекта

2022-04-07 21:21 UTC, merged